const associateId='matechreviews-20';
const items=[
['bags','Your main bag','Choose a carry-on or checked bag that fits your airline’s current size rules.','Samsonite Omni 2 carry on luggage'],['bags','Personal-item backpack','Keep your documents, medication, valuables, and one change of clothes close.','travel personal item backpack airline'],['bags','Packing cubes','Group clothing by type or day so your bag is easier to unpack.','Eagle Creek Pack It packing cubes'],['bags','Luggage scale','Weigh your bag at home and avoid surprises at the airport.','Etekcity digital luggage scale'],
['documents','Passport holder','Keep passport, boarding passes, and cards together—without blocking access at security.','RFID passport holder travel wallet'],['documents','Luggage tags','Add contact details to checked luggage; use information you are comfortable sharing.','privacy luggage tags'],['documents','TSA-approved locks','Useful for some checked bags; check the lock and airline rules for your trip.','TSA approved luggage locks'],['documents','Bluetooth item tracker','Helpful for locating a bag; check phone compatibility and airline battery policies.','Apple AirTag 4 pack'],
['tech','Universal travel adapter','Match the plug type to your destination. An adapter does not always convert voltage.','EPICKA universal travel adapter'],['tech','Portable power bank','Keep a phone charged in transit. Carry spare lithium batteries in your cabin bag.','Anker Nano Power Bank 10000mAh 30W'],['tech','Multi-port USB charger','Reduce the number of wall chargers you bring; confirm the wattage your laptop needs.','Anker Prime 100W GaN charger'],['tech','Noise-cancelling earbuds','Useful for flights and shared spaces; choose a fit you will actually wear.','Apple AirPods Pro 2 USB-C'],
['comfort','Travel pillow','Helpful on longer flights or road trips; choose one that fits your sleeping style.','memory foam travel neck pillow'],['comfort','Eye mask and earplugs','A small, low-cost way to make unfamiliar rooms or flights more comfortable.','sleep eye mask earplugs travel'],['comfort','Refillable water bottle','Fill it after security to stay hydrated while avoiding single-use bottles.','Owala FreeSip water bottle 24 oz'],['comfort','Compression socks','Some travelers use these on longer trips; ask a clinician if you have health concerns.','compression socks travel'],
['toiletries','Clear toiletry bag','Keep liquids together and check airport liquid rules before you pack.','TSA approved clear toiletry bag'],['toiletries','Leakproof travel bottles','Decant only what you need, and seal liquids in a separate bag.','leakproof travel bottles TSA'],['toiletries','Quick-dry towel','Useful for beach, hostel, gym, or unexpected rain.','Rainleaf microfiber travel towel'],['toiletries','Laundry bag','Keeps worn clothes away from clean clothing inside your suitcase.','travel laundry bag'],
['outdoors','Packable daypack','A light extra bag for day trips, snacks, a layer, and a water bottle.','packable travel daypack'],['outdoors','Waterproof dry bag','Protects small items around water; pick a size for your activity.','HEETA waterproof dry bag'],['outdoors','Packable rain jacket','Check the forecast and use a compact outer layer instead of hoping for good weather.','packable rain jacket travel'],['outdoors','Waterproof phone pouch','An optional backup for beach, boating, or rainy outings.','waterproof phone pouch travel']
];
const categories={all:'Everything',bags:'Bags & organize',documents:'Documents & safety',tech:'Tech & power',comfort:'Flight comfort',toiletries:'Toiletries',outdoors:'Outdoors'};
const categoryImages={bags:['https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1553531889-56e0c7f4bd33?auto=format&fit=crop&w=760&q=80'],documents:['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=760&q=80'],tech:['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=760&q=80'],comfort:['https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=760&q=80'],toiletries:['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=760&q=80'],outdoors:['https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=760&q=80','https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=760&q=80']};
const itemImages={
  'Your main bag':'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=760&q=80','Personal-item backpack':'https://images.unsplash.com/photo-1553531889-56e0c7f4bd33?auto=format&fit=crop&w=760&q=80','Packing cubes':'https://images.pexels.com/photos/18999368/pexels-photo-18999368.jpeg?auto=compress&cs=tinysrgb&w=760','Luggage scale':'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=760&q=80',
  'Passport holder':'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=760&q=80','Luggage tags':'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=760&q=80','TSA-approved locks':'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=760&q=80','Bluetooth item tracker':'https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=760&q=80',
  'Universal travel adapter':'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=760&q=80','Portable power bank':'https://unsplash.com/photos/nM5eVYJZ5jg/download?force=true&w=760','Multi-port USB charger':'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=760&q=80','Noise-cancelling earbuds':'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=760&q=80',
  'Travel pillow':'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=760&q=80','Eye mask and earplugs':'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=760&q=80','Refillable water bottle':'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=760&q=80','Compression socks':'https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=760&q=80',
  'Clear toiletry bag':'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=760&q=80','Leakproof travel bottles':'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=760&q=80','Quick-dry towel':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=760&q=80','Laundry bag':'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=760&q=80',
  'Packable daypack':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=760&q=80','Waterproof dry bag':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=760&q=80','Packable rain jacket':'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=760&q=80','Waterproof phone pouch':'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=760&q=80'};
const saved=new Set(JSON.parse(localStorage.getItem('packcheck-items')||'[]'));let active='all';
function url(q){return `https://www.amazon.com/s?k=${encodeURIComponent(q)}&tag=${associateId}`}
function render(){const shown=active==='all'?items:items.filter(x=>x[0]===active);document.getElementById('packing-grid').innerHTML=shown.map((x,i)=>{const id=items.indexOf(x);const image=itemImages[x[1]]||categoryImages[x[0]][id%2];return `<article class="pack-card"><img class="pack-card-image" src="${image}" alt="${x[1]} travel item" loading="lazy"><div class="pack-card-body"><label><input type="checkbox" data-id="${id}" ${saved.has(id)?'checked':''}> I already packed this</label><h3>${x[1]}</h3><p>${x[2]}</p><a href="${url(x[3])}" target="_blank" rel="nofollow sponsored noopener">Check price on Amazon ↗</a><span class="commission">Affiliate link — we may earn a commission.</span></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(e=>e.addEventListener('change',()=>{const id=+e.dataset.id;e.checked?saved.add(id):saved.delete(id);localStorage.setItem('packcheck-items',JSON.stringify([...saved]));progress()}));progress()}
function progress(){document.getElementById('progress-number').textContent=`${saved.size} / ${items.length}`;document.getElementById('progress-bar').style.width=`${saved.size/items.length*100}%`}
document.getElementById('category-tabs').innerHTML=Object.entries(categories).map(([k,v])=>`<button data-tab="${k}" class="${k===active?'active':''}">${v}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));render()}));document.querySelectorAll('[data-filter]').forEach(a=>a.addEventListener('click',()=>{active=a.dataset.filter||'all';document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===active));render()}));document.getElementById('reset-list').addEventListener('click',()=>{saved.clear();localStorage.removeItem('packcheck-items');render()});document.getElementById('year').textContent=new Date().getFullYear();render();
